version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Para evitar que o node_modules local sobrescreva o do container
    environment:
      - NODE_ENV=development
    # Adicione aqui dependências de outros serviços, como banco de dados
    # depends_on:
    #   - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Metro Bundler
      - "19000:19000" # Expo Go (se usado)
      - "19001:19001" # Expo Go
      - "19002:19002" # Expo Web (se usado)
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0

  # Descomente e configure se precisar de um banco de dados PostgreSQL
  # db:
  #   image: postgres:13-alpine
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=quantzauser
  #     - POSTGRES_PASSWORD=quantzapass
  #     - POSTGRES_DB=quantzadb

# Descomente se precisar de volumes persistentes para o banco de dados
# volumes:
#   postgres_data:

